# .github/workflows/convert-to-pdf.yml

name: convert-to-pdf
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main

jobs:
  convert:
    name: convert-to-pdf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: .
          output_dir: .
          images_dir: .
          # Default is true, can set to false to only get PDF files
          build_html: false

      - run: mv README.pdf 2021-test.pdf

      - uses: actions/upload-artifact@v1
        with:
          name: artifacts
          path: 2021-test.pdf