name: publish
on:
  workflow_dispatch:
    # for manual trigger

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: src
          output_dir: .
          images_dir: .
          # Default is true, can set to false to only get PDF files
          build_html: false
          theme: theme.css

      - name: Install zenodraft
        shell: bash
        run: |
          npm install git+https://github.com/jspaaks/zenodraft
          export PATH=${PATH}:$(pwd)/node_modules/.bin

      - name: Upload to Zenodo Sandbox
        shell: bash
        env:
          ZENODO_SANDBOX_ACCESS_TOKEN: ${{ secrets.ZENODO_SANDBOX_ACCESS_TOKEN }}
        run: |
         zenodraft --sandbox deposition create in-existing-collection 831247
         LATEST_ID=$(zenodraft --sandbox deposition latest 831247)
         zenodraft --sandbox file add $LATEST_ID 2021-test.pdf
         zenodraft --sandbox metadata update $LATEST_ID .zenodo.json
