name: publish
on:
  release:
    types: [published]
  workflow_dispatch:
    # for manual trigger

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: src
          output_dir: .
          images_dir: .
          # Default is true, can set to false to only get PDF files
          build_html: false
          theme: theme.css

      - name: Zenodo sandbox upload
        run: "npx --package @iomeg/zenodo-upload zenodo_upload --sandbox --no-checksum 831247 2021-test.pdf 1.1.0 $ZENODO_ACCESS_TOKEN"
