name: publish
on:
  release:
    types: [published]
  workflow_dispatch:
    # for manual trigger

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: src
          output_dir: .
          images_dir: .
          # Default is true, can set to false to only get PDF files
          build_html: false
          theme: theme.css

      - run: "echo 'TODO upload 2021-test.pdf to Zenodo using https://github.com/iomega/zenodo-upload'"
